const UserActionsType = {
    GOOGLE_SIGN_IN_START:"GOOGLE_SIGN_IN_START",
    SIGN_IN_SUCCESS:"SIGN_IN_SUCCESS",
    SIGN_IN_FAILED:"SIGN_IN_FAILED",
    CHECK_USER_SESSION:"CHECK_USER_SESSION",
    EMAIL_SIGN_IN_START:"EMAIL_SIGN_IN_START",
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILED: 'SIGN_OUT_FAILED',
    SIGN_UP_START:"SING_UP_START",
    SIGN_UP_SUCESS:"SING_UP_SUCCESS",
    SIGN_UP_FAILED: "SING_UP_FAILED"
};


export default UserActionsType;